version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "docs/",
  "dev/",
  "binder/"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true
