ignore-paths:
  - docs
  - versioneer.py
  - pypal/_version.py
  - pypal/pal/_hypervolume.py
  - pypal/models/coregionalized.pys

pylint:
  run: true

pyflakes:
  run: false

pep8:
  run: false

mccabe:
  run: false
