ignore-paths:
  - docs
  - versioneer.py
  - pyepal/_version.py
  - pyepal/pal/_hypervolume.py
  - pyepal/models/coregionalized.py

pylint:
  run: true

pyflakes:
  run: false

pep8:
  run: false

mccabe:
  run: false
